# Creating object of SessionLocal and then we can use it in our app for database connection
# Everytime you connect to something that is a session
# to create a session we have sessionmaker
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine

# sessionmaker has parameters
# Whenever we do database transactions noramlly we have to do commits for it but by default it will be autocommit=false and we can set to false or true
#autoflush is a configuration setting that forces the Session to automatically write pending in-memory data changes to the database transaction immediately before any new query is executed.
# passing bind=engine into sessionmaker links your database driver configurations directly to your session factory. This setting ensures that every individual Session instance generated by that factory automatically knows which database to communicate with and where to request connection resources.
#When Session = sessionmaker(bind=engine) is called, you are establishing a default database target. Whenever a newly generated session needs to execute a query or flush data, it silently goes to that specific engine, checks out a physical connection, runs the SQL, and returns the connection to the pool when done.

db_url = "postgresql://postgres:12345678@localhost:5432/FASTAPI_Practice"

engine = create_engine(db_url)

Session = sessionmaker(autocommit=False, autoflush=False, bind=engine)

## Go to where you want to use your db (main.py in this case)
# import database session from the dbconfig using "from dbconfig import session"
# make db session "db = session()" in any function inside endpoints
# Execute query by using "db.query(<query>)"

# We don't need to write actual SQL query because of SQLAlchemy. 
# Now for mapping the database and the class. The classes in models.py are pydantic. so we have to create another kind of class based on SQL Alchemy for database. So the database schema will be created based on that particular class.
# We can mention column types, name and some filters or special access like Foreign keys, Primary keys etc. We cant do that inside pydantic base model classes.
# So we need a class for data validation (Pydantic) and a seperate class for SQL Alchemy. 
# My pydanyic models are in models.py and SQL Alchemy models in dbModels.py for now.
# Now in main.py we can create tables according to our models in dbmodels.py and import engine from dbconfig
#import dbmodels
# Then I will say in main that hey use the metadata in dbmodels to create tables and bind to engine (main.py)
#dbmodels.Base.metadata.create_all(bind=engine)
